// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3FMg5j0Fvv916hyysum9jKnS6Ki0Us9E',
    appId: '1:305655368454:android:61a8000724f461822fac87',
    messagingSenderId: '305655368454',
    projectId: 'myproject-995da',
    storageBucket: 'myproject-995da.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4EUO3n_qzpxO_6vy_VZPKdL4eEIJm2-o',
    appId: '1:305655368454:ios:c5b6137837d376d22fac87',
    messagingSenderId: '305655368454',
    projectId: 'myproject-995da',
    storageBucket: 'myproject-995da.firebasestorage.app',
    iosBundleId: 'com.example.dushanApp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4EUO3n_qzpxO_6vy_VZPKdL4eEIJm2-o',
    appId: '1:305655368454:ios:c5b6137837d376d22fac87',
    messagingSenderId: '305655368454',
    projectId: 'myproject-995da',
    storageBucket: 'myproject-995da.firebasestorage.app',
    iosBundleId: 'com.example.dushanApp1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBS5emXiJZGmU139_oVVlPvyC_Mnx_eGmI',
    appId: '1:305655368454:web:fa3177c2a3416f372fac87',
    messagingSenderId: '305655368454',
    projectId: 'myproject-995da',
    authDomain: 'myproject-995da.firebaseapp.com',
    storageBucket: 'myproject-995da.firebasestorage.app',
    measurementId: 'G-K88Q87GT7C',
  );
}
